language: python

python:
  - "2.6"
  - "2.7"
  - "pypy"

virtualenv:
  system_site_packages: true

env:
  - DJANGO=1.3.1


install:
  - pip install Django==$DJANGO APScheduler teamcity-messages django-piston nose python-daemon lockfile stdeb PyYAML
  - sudo apt-get install python-pycurl python-yaml python-lxml python-nose createrepo python-rpm

script: "python setup.py test"
