language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

env:
  - DJANGO=1.3.1

before_script:
  - sudo apt-get install python-pycurl python-yaml python-lxml python-nose createrepo python-rpm

install:
  - pip install Django==$DJANGO APScheduler teamcity-messages django-piston nose python-daemon lockfile stdeb PyYAML mockito

script: "python setup.py test"
